In [84]:
import pandas as pd

# Lakukan load data dari file “Ujian_Komprehensif.csv” ke dalam Pandas DataFrame, beri nama df_sp2020; 
df_sp2020 = pd.read_csv('Ujian_Komprehensif.csv', delimiter=';')

# Tampilkan 10 baris pertama dari DataFrame yang telah terbentuk; 
print(df_sp2020.head(10))

                        Provinsi           Pulau Post Generasi Z Generasi Z  \
0                       11. ACEH        SUMATERA         782.191  1.531.897
1             12. SUMATERA UTARA        SUMATERA       2.198.567  4.241.259
2             13. SUMATERA BARAT        SUMATERA         728.658  1.558.106
3                       14. RIAU        SUMATERA         975.045  1.831.988
4                      15. JAMBI        SUMATERA         501.619    975.166
5           16. SUMATERA SELATAN        SUMATERA       1.243.243  2.286.741
6                   17. BENGKULU        SUMATERA         280.112    553.664
7                    18. LAMPUNG        SUMATERA       1.247.288  2.375.721
8  19. KEPULAUAN BANGKA BELITUNG        SUMATERA         189.584    400.381
9             21. KEPULAUAN RIAU  KEPULAUAN RIAU         306.559    562.655

    Milenial Generasi X     Boomer Pre Boomer       Total
0  1.377.887    991.294    512.865     78.737   5.274.871
1  3.791.537  2.814.656  1.569.163    184.179  14.799.361
2  1.390.340  1.074.413    677.138    105.817   5.534.472
3  1.704.452  1.262.954    566.314     53.334   6.394.087
4    940.102    728.651    361.400     41.290   3.548.228
5  2.202.735  1.700.263    915.080    119.370   8.467.432
6    532.287    407.474    211.996     25.137   2.010.670
7  2.335.896  1.856.163  1.033.585    159.195   9.007.848
8    393.664    300.597    154.159     17.293   1.455.678
9    578.183    430.132    168.334     18.701   2.064.564

In [100]:

# Buatlah sebuah data frame baru dengan nama df_sp2020 dan pilih semua kolom kecuali kolom Total dan semua baris kecuali baris Total; 
df_sp2020 = df_sp2020.loc[
    df_sp2020['Provinsi'] != 'TOTAL',
    df_sp2020.columns != 'Total'
].copy()

df_sp2020

,Provinsi,Pulau,Post Generasi Z,Generasi Z,Milenial,Generasi X,Boomer,Pre Boomer
0,11. ACEH,SUMATERA,782.191,1.531.897,1.377.887,991.294,512.865,78.737
1,12. SUMATERA UTARA,SUMATERA,2.198.567,4.241.259,3.791.537,2.814.656,1.569.163,184.179
2,13. SUMATERA BARAT,SUMATERA,728.658,1.558.106,1.390.340,1.074.413,677.138,105.817
3,14. RIAU,SUMATERA,975.045,1.831.988,1.704.452,1.262.954,566.314,53.334
4,15. JAMBI,SUMATERA,501.619,975.166,940.102,728.651,361.400,41.290
5,16. SUMATERA SELATAN,SUMATERA,1.243.243,2.286.741,2.202.735,1.700.263,915.080,119.370
6,17. BENGKULU,SUMATERA,280.112,553.664,532.287,407.474,211.996,25.137
7,18. LAMPUNG,SUMATERA,1.247.288,2.375.721,2.335.896,1.856.163,1.033.585,159.195
8,19. KEPULAUAN BANGKA BELITUNG,SUMATERA,189.584,400.381,393.664,300.597,154.159,17.293
9,21. KEPULAUAN RIAU,KEPULAUAN RIAU,306.559,562.655,578.183,430.132,168.334,18.701
10,31. DKI JAKARTA,JAWA,1.291.532,2.678.252,2.816.278,2.404.005,1.227.534,144.487
11,32. JAWA BARAT,JAWA,6.212.835,12.965.399,12.653.335,10.169.066,5.600.895,672.632
12,33. JAWA TENGAH,JAWA,4.312.777,9.023.730,9.125.046,8.012.090,5.241.102,801.290
13,34. DI YOGYAKARTA,JAWA,391.116,835.000,859.386,823.953,619.663,139.601
14,35. JAWA TIMUR,JAWA,4.565.674,9.643.116,10.028.010,9.263.150,6.154.554,1.011.192
15,36. BANTEN,JAWA,1.675.105,3.264.335,3.258.101,2.454.483,1.138.713,113.825
16,51. BALI,BALI NUSRA,475.536,1.053.952,1.057.293,982.676,630.340,117.607
17,52. NUSA TENGGARA BARAT,BALI NUSRA,821.297,1.448.701,1.387.755,1.050.838,537.338,74.163
18,53. NUSA TENGGARA TIMUR,BALI NUSRA,879.410,1.569.178,1.316.510,914.174,551.055,95.239
19,61. KALIMANTAN BARAT,KALIMANTAN,750.200,1.521.612,1.452.788,1.071.008,546.225,72.557
20,62. KALIMANTAN TENGAH,KALIMANTAN,352.020,755.008,734.453,544.257,252.143,32.088
21,63. KALIMANTAN SELATAN,KALIMANTAN,606.227,1.092.878,1.051.899,848.903,425.910,47.767
22,64. KALIMANTAN TIMUR,KALIMANTAN,502.134,1.055.423,1.023.266,778.362,362.914,43.940
23,65. KALIMANTAN UTARA,KALIMANTAN,92.259,205.124,194.197,139.566,62.778,7.890
24,71. SULAWESI UTARA,SULAWESI,322.731,661.469,645.872,562.155,365.293,64.403
25,72. SULAWESI TENGAH,SULAWESI,438.554,843.569,775.178,583.232,306.709,38.492
26,73. SULAWESI SELATAN,SULAWESI,1.144.702,2.567.400,2.312.797,1.796.402,1.060.974,191.234
27,74. SULAWESI TENGGARA,SULAWESI,402.455,786.855,682.934,476.912,242.303,33.416
28,75. GORONTALO,SULAWESI,151.217,335.659,306.123,233.762,127.093,17.827
29,76. SULAWESI BARAT,SULAWESI,218.471,432.546,364.272,254.184,130.276,19.480
30,81. MALUKU,KEPULAUAN MALUKU,248.588,566.464,490.013,330.631,184.047,29.180
31,82. MALUKU UTARA,KEPULAUAN MALUKU,190.938,387.963,344.657,232.997,113.825,12.557
32,91. PAPUA BARAT,PAPUA,155.749,341.528,328.307,210.930,90.113,7.441
33,94. PAPUA,PAPUA,665.696,1.156.343,1.244.419,852.966,351.144,33.139

In [101]:
# Buatlah pivot table dengan nama df_pivot_milenial dari df_sp2020 dengan menerapkan aggregate function count, sum pada Generasi ‘Milenial’, dengan index Pulau. Lakukan penyesuaian tipe data dan cleansing agar dapat dilakukan kalkulasi; 

df_milenial = df_sp2020.loc[df_sp2020['Provinsi'] != 'TOTAL', ['Pulau', 'Milenial']].copy()
df_milenial['Milenial'] = pd.to_numeric(
	df_milenial['Milenial'].astype(str).str.replace('.', '', regex=False),
	errors='coerce'
)
df_pivot_milenial = df_milenial.pivot_table(
	values='Milenial',
	index='Pulau',
	aggfunc=['count', 'sum']
)
df_pivot_milenial

                    count       sum
                 Milenial  Milenial
Pulau
BALI NUSRA              3   3761558
JAWA                    6  38740156
KALIMANTAN              5   4456603
KEPULAUAN MALUKU        2    834670
KEPULAUAN RIAU          1    578183
PAPUA                   2   1572726
SULAWESI                6   5087176
SUMATERA                9  14668900

In [87]:
# Buatlah pivot table dengan nama df_pivot_post_Z dari df_sp2020 dengan menerapkan aggregate function count, sum pada Generasi ‘Post Generasi Z’, dengan index Pulau. Lakukan penyesuaian tipe data dan cleansing agar dapat dilakukan kalkulasi; 

df_post_Z = df_sp2020.loc[df_sp2020['Provinsi'] != 'TOTAL', ['Pulau', 'Post Generasi Z']].copy()
df_post_Z['Post Generasi Z'] = pd.to_numeric(
	df_post_Z['Post Generasi Z'].astype(str).str.replace('.', '', regex=False),
	errors='coerce'
)
df_pivot_post_Z = df_post_Z.pivot_table(
	values='Post Generasi Z',
	index='Pulau',
	aggfunc=['count', 'sum']
)
df_pivot_post_Z

                           count             sum
                 Post Generasi Z Post Generasi Z
Pulau
BALI NUSRA                     3         2176243
JAWA                           6        18449039
KALIMANTAN                     5         2302840
KEPULAUAN MALUKU               2          439526
KEPULAUAN RIAU                 1          306559
PAPUA                          2          821445
SULAWESI                       6         2678130
SUMATERA                       9         8146307

In [88]:
# Buatlah DataFrame gabungan dengan nama df_pivot_milenial_post_Z dengan nama kolom 'Count_Milenial', 'Sum_Milenial', 'Count_Post_Z', 'Sum_Post_Z'; 

df_pivot_milenial_post_Z = pd.concat([df_pivot_milenial, df_pivot_post_Z], axis=1)
df_pivot_milenial_post_Z

                    count       sum           count             sum
                 Milenial  Milenial Post Generasi Z Post Generasi Z
Pulau
BALI NUSRA              3   3761558               3         2176243
JAWA                    6  38740156               6        18449039
KALIMANTAN              5   4456603               5         2302840
KEPULAUAN MALUKU        2    834670               2          439526
KEPULAUAN RIAU          1    578183               1          306559
PAPUA                   2   1572726               2          821445
SULAWESI                6   5087176               6         2678130
SUMATERA                9  14668900               9         8146307

In [89]:
# Simpan df_pivot_milenial_post_Z ke dalam file csv dengan delimiter "|" dan penamaan jawaban_bag1_[nip].csv (ganti [nip] dengan NIP 18-digit Anda). 

df_pivot_milenial_post_Z.to_csv(f'jawaban_bag1_198605252006021005.csv', sep='|', index=True)

#Bagian Ke 2

In [90]:
# Salin DataFrame df_sp2020 ke dalam DataFrame baru bernama df_sp2020_2. Lakukan penyesuaian tipe data dan cleansing agar dapat dilakukan kalkulasi. Buatlah kolom baru dengan nama ‘TOTAL PENDUDUK’ pada df_sp2020_2. Kolom tersebut berisi jumlah penduduk untuk semua generasi per Provinsi; 

df_sp2020_2 = df_sp2020.copy()
kolom_generasi = [
    'Post Generasi Z', 'Generasi Z', 'Milenial',
    'Generasi X', 'Boomer', 'Pre Boomer'
]

df_sp2020_2[kolom_generasi] = df_sp2020_2[kolom_generasi].apply(
    lambda kolom: pd.to_numeric(
        kolom.astype(str).str.replace('.', '', regex=False),
        errors='coerce'
    )
)
df_sp2020_2['TOTAL PENDUDUK'] = df_sp2020_2[kolom_generasi].sum(axis=1)
df_sp2020_2['TOTAL PENDUDUK'].head(10)

0     5274871
1    14799361
2     5534472
3     6394087
4     3548228
5     8467432
6     2010670
7     9007848
8     1455678
9     2064564
Name: TOTAL PENDUDUK, dtype: int64

In [91]:
# Buatlah kolom baru pada df_sp2020 dengan nama ‘Kategori’. Kolom tersebut berisi kategori tingkat populasi dari kolom ‘TOTAL PENDUDUK’ dengan ketentuan sebagai berikut: 
# Kategori low adalah wilayah dengan populasi sampai dengan 3.000.000 penduduk; 
# Kategori mid adalah wilayah dengan populasi diatas 3.000.000 hingga 30.000.000 penduduk 
# Kategori high adalah wilayah dengan populasi di atas 30.000.0000 penduduk 
# (Bisa dengan membuat fungsi dan apply fungsi tersebut ke kolom ‘TOTAL PENDUDUK’); 

def kategori_populasi(total_penduduk):
    if total_penduduk <= 3000000:
        return 'low'
    elif 3000000 < total_penduduk <= 30000000:
        return 'mid'
    else:
        return 'high'

df_sp2020_2['Kategori'] = df_sp2020_2['TOTAL PENDUDUK'].apply(kategori_populasi)
df_sp2020_2['Kategori'].head(10)

0    mid
1    mid
2    mid
3    mid
4    mid
5    mid
6    low
7    mid
8    low
9    low
Name: Kategori, dtype: str

In [92]:
# Buat kolom baru dengan nama ‘kode_prop’ yang berisi angka kode propinsi yang diekstrak dari kolom ‘Provinsi’; 

df_sp2020_2['kode_prop'] = df_sp2020_2['Provinsi'].str.extract(r'(\d+)')[0].astype('Int64')
df_sp2020_2['kode_prop'].head(10)

0    11
1    12
2    13
3    14
4    15
5    16
6    17
7    18
8    19
9    21
Name: kode_prop, dtype: Int64

In [93]:
# Bersihkan angka didepan kolom ‘Provinsi’ sehingga hanya berisi nama provinsi saja tidak mengandung angka maupun titik; 

df_sp2020_2['Provinsi'] = df_sp2020_2['Provinsi'].str.replace(r'^\d+\.\s*', '', regex=True)
df_sp2020_2['Provinsi'].head(10)

0                         ACEH
1               SUMATERA UTARA
2               SUMATERA BARAT
3                         RIAU
4                        JAMBI
5             SUMATERA SELATAN
6                     BENGKULU
7                      LAMPUNG
8    KEPULAUAN BANGKA BELITUNG
9               KEPULAUAN RIAU
Name: Provinsi, dtype: str

In [94]:
# Lakukan pivot (beri nama df_pivot_bag2) pada DataFrame dan urutkan ascending berdasarkan Provinsi sehingga terbentuk pivot seperti Gambar 2.; 
# hasilnya berupa kategori dan jumlah propinsi yang masuk ke dalam kategori tersebut.

df_sp2020_2['Kategori'] = df_sp2020_2['TOTAL PENDUDUK'].apply(kategori_populasi)

df_pivot_bag2 = (
    df_sp2020_2.loc[df_sp2020_2['Provinsi'] != 'TOTAL']
    .pivot_table(index='Kategori', values='Provinsi', aggfunc='count')
    .sort_values(by='Provinsi', ascending=True)
)
df_pivot_bag2

          Provinsi
Kategori
high             3
low             13
mid             18

In [95]:
# Simpan pivot hasil soal nomor 5 tersebut ke dalam file csv dengan delimiter |" dan format penamaan jawaban_bag2_[nip].csv (ganti [nip] dengan NIP 18-digit Anda). 

df_pivot_bag2.to_csv(f'jawaban_bag2_198605252006021005.csv', sep='|', index=True)

Bagian Ke-3

In [96]:
# Buat dataframe baru dengan nama df_3 yang berisi kolom 'kode_prop', 'Provinsi', 'Pulau', 'TOTAL PENDUDUK', 'Kategori' dari dataframe df_sp2020_2; 

df_3 = df_sp2020_2[['kode_prop', 'Provinsi', 'Pulau', 'TOTAL PENDUDUK', 'Kategori']].copy()
df_3

,kode_prop,Provinsi,Pulau,TOTAL PENDUDUK,Kategori
0,11,ACEH,SUMATERA,5274871,mid
1,12,SUMATERA UTARA,SUMATERA,14799361,mid
2,13,SUMATERA BARAT,SUMATERA,5534472,mid
3,14,RIAU,SUMATERA,6394087,mid
4,15,JAMBI,SUMATERA,3548228,mid
5,16,SUMATERA SELATAN,SUMATERA,8467432,mid
6,17,BENGKULU,SUMATERA,2010670,low
7,18,LAMPUNG,SUMATERA,9007848,mid
8,19,KEPULAUAN BANGKA BELITUNG,SUMATERA,1455678,low
9,21,KEPULAUAN RIAU,KEPULAUAN RIAU,2064564,low
10,31,DKI JAKARTA,JAWA,10562088,mid
11,32,JAWA BARAT,JAWA,48274162,high
12,33,JAWA TENGAH,JAWA,36516035,high
13,34,DI YOGYAKARTA,JAWA,3668719,mid
14,35,JAWA TIMUR,JAWA,40665696,high
15,36,BANTEN,JAWA,11904562,mid
16,51,BALI,BALI NUSRA,4317404,mid
17,52,NUSA TENGGARA BARAT,BALI NUSRA,5320092,mid
18,53,NUSA TENGGARA TIMUR,BALI NUSRA,5325566,mid
19,61,KALIMANTAN BARAT,KALIMANTAN,5414390,mid
20,62,KALIMANTAN TENGAH,KALIMANTAN,2669969,low
21,63,KALIMANTAN SELATAN,KALIMANTAN,4073584,mid
22,64,KALIMANTAN TIMUR,KALIMANTAN,3766039,mid
23,65,KALIMANTAN UTARA,KALIMANTAN,701814,low
24,71,SULAWESI UTARA,SULAWESI,2621923,low
25,72,SULAWESI TENGAH,SULAWESI,2985734,low
26,73,SULAWESI SELATAN,SULAWESI,9073509,mid
27,74,SULAWESI TENGGARA,SULAWESI,2624875,low
28,75,GORONTALO,SULAWESI,1171681,low
29,76,SULAWESI BARAT,SULAWESI,1419229,low
30,81,MALUKU,KEPULAUAN MALUKU,1848923,low
31,82,MALUKU UTARA,KEPULAUAN MALUKU,1282937,low
32,91,PAPUA BARAT,PAPUA,1134068,low
33,94,PAPUA,PAPUA,4303707,mid

In [97]:
# Gunakan salah satu metode outlier detection untuk mendeteksi apakah kolom ‘TOTAL PENDUDUK’ masuk dalam kategori ‘Outlier’ atau ‘Not Outlier’ dan tampung hasilnya dalam kolom baru bernama ‘result_outlier’;

df_3['result_outlier'] = df_3['TOTAL PENDUDUK'].apply(lambda x: 'Outlier' if x > df_3['TOTAL PENDUDUK'].quantile(0.75) + 1.5 * (df_3['TOTAL PENDUDUK'].quantile(0.75) - df_3['TOTAL PENDUDUK'].quantile(0.25)) else 'Not Outlier')
df_3

,kode_prop,Provinsi,Pulau,TOTAL PENDUDUK,Kategori,result_outlier
0,11,ACEH,SUMATERA,5274871,mid,Not Outlier
1,12,SUMATERA UTARA,SUMATERA,14799361,mid,Not Outlier
2,13,SUMATERA BARAT,SUMATERA,5534472,mid,Not Outlier
3,14,RIAU,SUMATERA,6394087,mid,Not Outlier
4,15,JAMBI,SUMATERA,3548228,mid,Not Outlier
5,16,SUMATERA SELATAN,SUMATERA,8467432,mid,Not Outlier
6,17,BENGKULU,SUMATERA,2010670,low,Not Outlier
7,18,LAMPUNG,SUMATERA,9007848,mid,Not Outlier
8,19,KEPULAUAN BANGKA BELITUNG,SUMATERA,1455678,low,Not Outlier
9,21,KEPULAUAN RIAU,KEPULAUAN RIAU,2064564,low,Not Outlier
10,31,DKI JAKARTA,JAWA,10562088,mid,Not Outlier
11,32,JAWA BARAT,JAWA,48274162,high,Outlier
12,33,JAWA TENGAH,JAWA,36516035,high,Outlier
13,34,DI YOGYAKARTA,JAWA,3668719,mid,Not Outlier
14,35,JAWA TIMUR,JAWA,40665696,high,Outlier
15,36,BANTEN,JAWA,11904562,mid,Not Outlier
16,51,BALI,BALI NUSRA,4317404,mid,Not Outlier
17,52,NUSA TENGGARA BARAT,BALI NUSRA,5320092,mid,Not Outlier
18,53,NUSA TENGGARA TIMUR,BALI NUSRA,5325566,mid,Not Outlier
19,61,KALIMANTAN BARAT,KALIMANTAN,5414390,mid,Not Outlier
20,62,KALIMANTAN TENGAH,KALIMANTAN,2669969,low,Not Outlier
21,63,KALIMANTAN SELATAN,KALIMANTAN,4073584,mid,Not Outlier
22,64,KALIMANTAN TIMUR,KALIMANTAN,3766039,mid,Not Outlier
23,65,KALIMANTAN UTARA,KALIMANTAN,701814,low,Not Outlier
24,71,SULAWESI UTARA,SULAWESI,2621923,low,Not Outlier
25,72,SULAWESI TENGAH,SULAWESI,2985734,low,Not Outlier
26,73,SULAWESI SELATAN,SULAWESI,9073509,mid,Not Outlier
27,74,SULAWESI TENGGARA,SULAWESI,2624875,low,Not Outlier
28,75,GORONTALO,SULAWESI,1171681,low,Not Outlier
29,76,SULAWESI BARAT,SULAWESI,1419229,low,Not Outlier
30,81,MALUKU,KEPULAUAN MALUKU,1848923,low,Not Outlier
31,82,MALUKU UTARA,KEPULAUAN MALUKU,1282937,low,Not Outlier
32,91,PAPUA BARAT,PAPUA,1134068,low,Not Outlier
33,94,PAPUA,PAPUA,4303707,mid,Not Outlier

In [98]:
# Terapkan metode label encoding untuk mentransformasi isi kolom ‘result_outlier’ dengan ketentuan ‘Outlier’ menjadi 1 dan ‘Not oulier’ menjadi 0 dan tampung hasilnya dalam kolom bernama ‘is_outlier’; 

df_3['is_outlier'] = df_3['result_outlier'].map({'Outlier': 1, 'Not Outlier': 0})
df_3

,kode_prop,Provinsi,Pulau,TOTAL PENDUDUK,Kategori,result_outlier,is_outlier
0,11,ACEH,SUMATERA,5274871,mid,Not Outlier,0
1,12,SUMATERA UTARA,SUMATERA,14799361,mid,Not Outlier,0
2,13,SUMATERA BARAT,SUMATERA,5534472,mid,Not Outlier,0
3,14,RIAU,SUMATERA,6394087,mid,Not Outlier,0
4,15,JAMBI,SUMATERA,3548228,mid,Not Outlier,0
5,16,SUMATERA SELATAN,SUMATERA,8467432,mid,Not Outlier,0
6,17,BENGKULU,SUMATERA,2010670,low,Not Outlier,0
7,18,LAMPUNG,SUMATERA,9007848,mid,Not Outlier,0
8,19,KEPULAUAN BANGKA BELITUNG,SUMATERA,1455678,low,Not Outlier,0
9,21,KEPULAUAN RIAU,KEPULAUAN RIAU,2064564,low,Not Outlier,0
10,31,DKI JAKARTA,JAWA,10562088,mid,Not Outlier,0
11,32,JAWA BARAT,JAWA,48274162,high,Outlier,1
12,33,JAWA TENGAH,JAWA,36516035,high,Outlier,1
13,34,DI YOGYAKARTA,JAWA,3668719,mid,Not Outlier,0
14,35,JAWA TIMUR,JAWA,40665696,high,Outlier,1
15,36,BANTEN,JAWA,11904562,mid,Not Outlier,0
16,51,BALI,BALI NUSRA,4317404,mid,Not Outlier,0
17,52,NUSA TENGGARA BARAT,BALI NUSRA,5320092,mid,Not Outlier,0
18,53,NUSA TENGGARA TIMUR,BALI NUSRA,5325566,mid,Not Outlier,0
19,61,KALIMANTAN BARAT,KALIMANTAN,5414390,mid,Not Outlier,0
20,62,KALIMANTAN TENGAH,KALIMANTAN,2669969,low,Not Outlier,0
21,63,KALIMANTAN SELATAN,KALIMANTAN,4073584,mid,Not Outlier,0
22,64,KALIMANTAN TIMUR,KALIMANTAN,3766039,mid,Not Outlier,0
23,65,KALIMANTAN UTARA,KALIMANTAN,701814,low,Not Outlier,0
24,71,SULAWESI UTARA,SULAWESI,2621923,low,Not Outlier,0
25,72,SULAWESI TENGAH,SULAWESI,2985734,low,Not Outlier,0
26,73,SULAWESI SELATAN,SULAWESI,9073509,mid,Not Outlier,0
27,74,SULAWESI TENGGARA,SULAWESI,2624875,low,Not Outlier,0
28,75,GORONTALO,SULAWESI,1171681,low,Not Outlier,0
29,76,SULAWESI BARAT,SULAWESI,1419229,low,Not Outlier,0
30,81,MALUKU,KEPULAUAN MALUKU,1848923,low,Not Outlier,0
31,82,MALUKU UTARA,KEPULAUAN MALUKU,1282937,low,Not Outlier,0
32,91,PAPUA BARAT,PAPUA,1134068,low,Not Outlier,0
33,94,PAPUA,PAPUA,4303707,mid,Not Outlier,0

In [99]:
# Simpan DataFrame hasil soal nomor 3 tersebut ke dalam file csv dengan delimiter ";" dan format penamaan jawaban_bag3_[nip].csv (ganti [nip] dengan NIP 18-digit Anda); 

df_3.to_csv(f'jawaban_bag3_198605252006021005.csv', sep=';', index=False)